### PR TITLE
Simplify Java rootfs/appfs build with Maven; add Java thumbnail, extract img metadata, and ocr appfs

### PR DESCRIPTION
**Pull request by linanqinqin**
- Simplify Java rootfs/appfs build workflow with Maven so that we don't need to manually configure Java dependencies such as providing standalone jar files. 

- Add three Java functions: thumbnail, extract image metadata, and ocr

### CODE REVIEW

**Comment by tan-yue** [comment]
Great! Now we upgrade java runtime and apps to be built with industry standard java. Where are the runtimes optimized for regular and fullapp?

**Comment by linanqinqin** [comment]
@tan-yue I am still working on regular and fullapp runtimes, will push them soon

**Comment by tan-yue** [comment]
Hi @linanqinqin ,
1. Is it possible to move the vsock code to the `common` directory? The three versions now contain duplicate vsock implementation.
2. What are the purpose of `app/src/main/java/srv/workload.java` in the `fullapp` and `regular` directories? Are they required to compile java runtimes? I think for these two versions, we have copied over function code at the time when we build the runtime.

**Comment by linanqinqin** [comment]
> Hi @linanqinqin ,
> 
> 1. Is it possible to move the vsock code to the `common` directory? The three versions now contain duplicate vsock implementation.
> 2. What are the purpose of `app/src/main/java/srv/workload.java` in the `fullapp` and `regular` directories? Are they required to compile java runtimes? I think for these two versions, we have copied over function code at the time when we build the runtime.

Hi @tan-yue ,

1. The vosck folder is in fact a submodule of the runtime parent module, and for Maven, the submodule has to be "relative" to the parent, meaning that the path to the submodule must be a relative path from the parent, for example, we can specify the submodule as "../../common/vsock", but I doubt that this is a correct path when we run inside docker. Another way to do the moving is that we have one vsock folder under common, and we copy it over before maven compilation. But this would make the runtime module for each version not self-explainable (the parent pom file specifies the vsock submodule but it's not there)

2. Those are placeholders for the purpose of compiling Java runtime. But if the appfs is copied before compiling runtime, there might be a way to eliminate this, though I don't think this would impact performance since it's only for compilation. At runtime, the workload directly imports the app

**Comment by linanqinqin** [comment]
@tan-yue Your second concern is now resolved. I have removed those placeholders (the app submodule) for compilation.

**Pull request merged**
