### PR TITLE
Reorganize snapfaas-images for fair comparison

### PR DESCRIPTION
**Pull request by tan-yue**
This branch contain the following updates:
1. all root filesystem directories are now under `rootfs`.

2. `rootfs` contains three versions of root filesystems: `snapfaas`, `fullapp`, and `regular`. `snapfaas` was the old `separate` and `fullapp` and `regular` was the old `combined` but now the two are separated to allow `regular` wrapper scripts to contain no snapshotting point.

3. all three versions of root filesystems now use the same `prelude.sh` and `postscript.sh` placed in `rootfs/common`.

4. now for all three versions, the open-rc task serverless-workload directly executes each runtime's `workload.sh`. See `rootfs/common/prelude.sh` for what is serverless-workload. The command `/bin/workload` is created by doing `cat {regular, fullapp, snapfaas}/{nodejs, python3}/workload.sh > /bin/workload`. This gets rid of one layer of unnecessary indirection.

TODO:
1. adjust java accordingly @linanqinqin 
2. make sure python3 code are precompiled

### CODE REVIEW

**Review by alevy — APPROVED** [review]

**Comment by alevy** [comment]
I think we may as well also delete any of the runtimes we're not actually using. They're in the git history, so we can always refer back to them.

**Comment by tan-yue** [comment]
> I think we may as well also delete any of the runtimes we're not actually using. They're in the git history, so we can always refer back to them.

currently I moved all unused runtimes to `.archived` folder.

**Comment by tan-yue** [comment]
@alevy I just thought of that for fair comparison it’s better to remove unnecessary imports? For example, python3 regular wrapper script does not need the built-in `os` module. nor the `subprocess` module's `run` or `Popen` And the `sys` module can be removed by using `PYTHONPATH`

**Comment by alevy** [comment]
@tan-yue yeah that's right

**Pull request merged**
